<script type="text/javascript">
    //<![CDATA[ 
    // Bind tab changes
    function bindActiveBrandTab(event) {
        if(event.tab && event.tab.name && $('store_switcher')){
            $('store_switcher').switchParams = 'active_tab/'+event.tab.name+'/';
        }
    }
    varienGlobalEvents.attachEventHandler('showTab', bindActiveBrandTab);

    // bind active tab
    <?php if($tabsBlock = $this->getLayout()->getBlock('brand_tabs')): ?>
    if(<?php echo $tabsBlock->getJsObjectName() ?> && <?php echo $tabsBlock->getJsObjectName() ?>.activeTab && $('store_switcher')){
        $('store_switcher').switchParams = 'active_tab/'+<?php echo $tabsBlock->getJsObjectName() ?>.activeTab.name+'/';
    }
    <?php endif; ?>
    //]]>
</script>
