<?php
/**
 * @var $this Astrio_QuickView_Block_Init
 */

$config = array();

/** @var Astrio_QuickView_Helper_Data $helper */
$helper = $this->helper('astrio_quickview');

$config['url'] = $helper->getUrl();
$config['link_class'] = $helper->getLinkClass(false);
?>
<script type="text/javascript">
    //<![CDATA[
    jQuery(function($) {
        $.productQuickView(<?php echo Mage::helper('core')->jsonEncode($config)?>);
    });
    //]]>
</script>