<?php
/**
 * @see
 * @var Mage_Adminhtml_Block_Catalog_Product
 *
 * @var $this Astrio_News_Block_Adminhtml_News
 */
?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="width:50%;"><h3 class="icon-head head-news"><?php echo Mage::helper('astrio_news')->__('Manage News') ?></h3></td>
            <td class="a-right">
                <?php echo $this->getButtonsHtml() ?>
            </td>
        </tr>
    </table>
</div>
<?php if( !$this->isSingleStoreMode() ): ?>
    <?php echo $this->getChildHtml('store_switcher');?>
<?php endif;?>
<div>
    <?php echo $this->getGridHtml() ?>
</div>
