<?php
/**
 * @var $this Astrio_Core_Block_Adminhtml_System_Config_Form_Field_Multiline_Html
 */

$_elementLabel = (string) $this->getElement()->getFieldConfig()->label;
$_elementLabel = $_elementLabel ? $_elementLabel : "Multi Line";

$divElementId = 'field_multiline_' . $this->getElement()->getId();
?>

<script type="text/javascript">
    //<![CDATA[
    function addLineToMultiline(elementId) {
        Element.insert($('line_container_' + elementId), {bottom: $('line_template_' + elementId).innerHTML});
    }
    function removeLineFromMultiline(button) {
        Element.remove(button.up().parentNode);
    }
    //]]>
</script>

<div class="entry-edit profile-generator" style="margin: 12px 0 0 0;">
    <div id="<?php echo $divElementId ?>">
        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__($_elementLabel) ?></h4>
        </div>
        <fieldset>
            <legend><?php echo $this->__($_elementLabel) ?></legend>
            <div class="profile_entity_type_product">
                <table style="display:none">
                    <tbody id="line_template_<?php echo $this->getElement()->getId() ?>">
                    <tr>
                        <td><input class="input-text" name="<?php echo $this->getElement()->getName() ?>[]" style="width:98%;"/></td>
                        <td><?php echo $this->getRemoveMapButtonHtml() ?></td>
                    </tr>
                    </tbody>
                </table>
                <table style="width:100%;">
                    <colgroup>
                        <col style="width: 85%"/>
                        <col style="width: 15%"/>
                    </colgroup>
                    <tbody id="line_container_<?php echo $this->getElement()->getId() ?>">
                    <?php if ($this->getValue()):?>
                        <?php foreach ($this->getValue() as $_rowValue): ?>
                            <tr>
                                <td><input class="input-text" name="<?php echo $this->getElement()->getName() ?>[]" value="<?php echo $_rowValue ?>" style="width:98%;"/></td>
                                <td><?php echo $this->getRemoveMapButtonHtml() ?></td>
                            </tr>
                        <?php endforeach ?>
                    <?php endif?>
                    </tbody>
                </table>
            </div>
            <?php echo $this->getAddMapButtonHtml() ?>
            <?php if ($this->getElement()->getComment()): ?>
                <p class="note"><span><?php echo $this->getElement()->getComment() ?></span></p>
            <?php endif ?>
        </fieldset>
    </div>

</div>

<script type="text/javascript">
    //<![CDATA[
    Element.show($('<?php echo $divElementId ?>'));
    var elems = Element.select('<?php echo $divElementId ?>', ['select', 'input', 'textarea', 'button', 'img']);
    elems.each(function (elem) {
        var isDisabled = <?php echo (int) $this->getDisabled() ?>;
        elem.disabled = isDisabled;
        if (isDisabled) {
            elem.addClassName('disabled');
        } else {
            elem.removeClassName('disabled');
        }
    });
    //]]>
</script>
