<?php
/**
 * @var $this Astrio_Core_Block_Adminhtml_Cache_Additional
 */
?>
<table class="form-list" style="margin-top: -5px;">
    <tr>
        <td class="scope-label">
            <button onclick="setLocation('<?php echo $this->getCleanImagesUrl()?>')" type="button" class="scalable delete">
                <span>
                    <span>
                        <span><?php echo Mage::helper('astrio_core')->__('Clean Unused Product Images') ?></span>
                    </span>
                </span>
            </button>
        </td>
        <td class="scope-label">
            <?php echo Mage::helper('astrio_core')->__('Remove Unused Product Images.')?>
        </td>
    </tr>
</table>
