<?php
/**
 * @var Astrio_Brand_Block_Brand_List $this
 * @var Astrio_Brand_Helper_Data $_brandsHelper
 * @var Astrio_Brand_Model_Brand $_brand
 */
$_brandsHelper = $this->helper('astrio_brand');
$_brands = $this->getCollection();
?>
<?php if (count($_brands) > 0): ?>
    <div class="page-title brand-title">
        <h1><?php echo $this->__('Brands') ?></h1>
    </div>
    <div class="block block-layered-nav">
        <div class="block-content">
            <div class="block-title">
                <strong>
                    <span><?php echo $this->__('Filter By:') ?></span>
                </strong>
            </div>
            <ul class="brand-left-menu">
                <dl id="narrow-by-list">
                    <dt class="odd"><?php echo $this->__('Brand') ?></dt>
                    <dd class="odd">
                        <ol>
                            <?php foreach ($_brands as $_brand): ?>
                                <li>
                                    <a href="<?php echo $_brand->getBrandUrl();?>">
                                        <?php echo $_brand->getName();?>
                                    </a>
                                </li>
                            <?php endforeach ?>

                            <!--li>
                                <a href="<?php echo $_brandsHelper->getBrandsListUrl() ?>">
                                    <?php echo $this->__('View All') ?>
                                </a>
                            </li-->
                        </ol>
                    </dd>
            </ul>
            </dl>
        </div>
    </div>
    <script type="text/javascript">decorateDataList('narrow-by-list')</script>
<?php endif ?>
